#!/bin/bash

# Jake Pauls
# https://jakepauls.dev
# https://github.com/jake-pauls

# Connects the dots...
# Assumptions: Clean Arch install with git and networking configured

###############
## Variables ##
###############
dpath=~/.dotfiles

cd ~ && echo "[warn] This install script assumes git is installed within a basic arch installation\n"

echo "[pacman] Checking for system updates..."
sudo pacman -Syu

#########
## SSH ##
#########
echo "[pacman] Installing openssh..."
sudo pacman -S openssh

echo "Please enter your GitHub email address: "
read gh_email

ssh-keygen -t ed25519 -C $gh_email
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_ed25519

echo "[warn] SSH key generated for this machine, in association with $gh_email."
echo "[warn] Add this public key to your GitHub account before continuing to configure SSH on this machine."

cat ~/.ssh/id_ed25519.pub

echo "Press [ENTER] to continue..."
read enter

# Update origin after SSH configuration
cd $dpath
git remote set-url origin git@github.com:jake-pauls/.dotfiles.git

###############
## .dotfiles ##
###############

# Symlink dotfiles
cd $dpath/scripts
bash confsym

###############
## yay (AUR) ##
###############
echo "[pacman] Installing the base-devel packages..."
sudo pacman -S base-devel
cd ~/.config

echo "[pacman] Cloning yay from the AUR..."
git clone https://aur.archlinux.org/yay.git
cd yay && makepkg -si
cd ~

##############
## Packages ##
##############

lib=(
    "clang"
)

file=(
    "pcmanfm"
    "zathura"
    "zathura-pdf-poppler"
    "sxiv"
)

# Replace "nvidia" with required graphics driver
display=(
    "nvidia"
    "xorg"
    "xorg-xinit"
    "picom"
    "nitrogen"
    "lxappearance"
)

environment=(
    "rofi"
    "awesome"
)

terminal=(
    "alacritty"
    "zsh"
    "starship"
)

cli=(
    "vim"
    "neovim"
    "ripgrep"
    "bat"
    "fd"
    "scrot"
    "xclip"
    "unzip"
)

misc=(
    "firefox"
    "discord"
    "volumeicon"
    "networkmanager"
)

yay=(
    "nerd-fonts-complete"
    "pfetch"
)


# Installation
sudo pacman -S ${lib[@]} ${file[@]} ${display[@]} ${environment[@]} ${terminal[@]} ${cli[@]} ${misc[@]}
yay -S ${yay[@]}

# Use dash as the default shell
echo "[info] Changing default shell to zsh"
sudo chsh -s /usr/bin/zsh

echo "[info] Successfully connected the dots."
echo "[info] Please reboot! Otherwise, happy hacking!"