#!/bin/sh

# Jake Pauls
# https://jakepauls.dev
# https://github.com/jake-pauls

# Connects the dots...
# Quick package installation procedure
# Assumptions: Clean Arch install with git and networking configured

###############
## Variables ##
###############
dpath=~/.dotfiles

cd ~ && echo "This install script assumes git is installed within a basic arch installation\n"

echo "Checking for system updates..."
sudo pacman -Syu

#########
## SSH ##
#########
echo "Installing openssh..."
sudo pacman -S openssh

echo "Please enter your GitHub email address: "
read gh_email

ssh-keygen -t ed25519 -C $gh_email
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_ed25519

echo "SSH key generated for this machine, in association with $gh_email"
echo "Add this public key to your GitHub account before continuing to configure SSH on this machine"

cat ~/.ssh/id_ed25519.pub

echo "Press [ENTER] to continue..."
read enter

# Update origin after SSH configuration
cd $dpath
git remote set-url origin git@github.com:jacob-pauls/.dotfiles.git

###############
## .dotfiles ##
###############

# Symlink dotfiles
cd $dpath/.scripts
confsym

###############
## yay (AUR) ##
###############
echo "Installing the base-devel packages..."
sudo pacman -S base-devel
cd ~/.config

echo "Cloning yay from the AUR..."
git clone https://aur.archlinux.org/yay.git
cd yay && makepkg -si
cd ~

##############
## Packages ##
##############

lib=(
    "nodejs"
    "npm"
    "clang"
)

file=(
    "ranger"
    "pcmanfm"
    "zathura"
    "zathura-pdf"
    "sxiv"
)

# Replace "nvidia" with required graphics driver
display=(
    "nvidia"
    "xorg"
    "xorg-xinit"
    "picom"
    "nitrogen"
    "lxappearance"
)

environment=(
    "dmenu"
    "awesome"
    "budgie-desktop"
    "gnome"
)

terminal=(
    "xterm"
    "alacritty"
    "dash"
    "zsh"
)

cli=(
    "vim"
    "ripgrep"
    "bat"
    "fd"
    "scrot"
    "xclip"
    "unzip"
)

misc=(
    "firefox"
    "discord"
    "networkmanager"
    "systemctl"
)

yay=(
    "neovim-nightly-bin"
    "nerd-fonts-complete"
    "ttf-ms-fonts"
)


# Installation
sudo pacman -S ${lib[@]} ${file[@]} ${display[@]} ${environment[@]} ${terminal[@]} ${cli[@]} ${misc[@]}
yay -S ${yay[@]}

# Use dash as the default shell
sudo chsh -s /usr/bin/dash

############
## Docker ##
############
while true; do
  read -p "Would you like to install and configure Docker? (uses systemd)" yn
  case $yn in
    [Yy]* ) sudo pacman -S docker; sudo systemctl enable docker.service; sudo systemctl enable docker.containerd.service; break;;
    [Nn]* ) exit;;
    * ) echo "Please answer yes (Y/y) or no (N/n).";;
  esac
done

echo "Successfully connected the dots."
echo "Please reboot! Otherwise, happy hacking!"
