#!/bin/bash

# Jake Pauls
# https://jakepauls.dev
# https://github.com/jake-pauls

# Removes existing files in home directory and symlinks files from .dotfiles repo
# Be mindful executing this, as its currently opinionated for a clean ArchLinux installation

# Variables
dotfiles_path=~/.dotfiles

# dotfiles to symlink
echo "Loading configured dotfiles..."
dotfiles=(
	".profile"
	".bashrc"
	".vimrc"
    ".zshrc"
    ".Xresources"
    ".xinitrc"
    ".config/nvim"
    ".config/zathura"
    ".config/git"
    ".config/fish"
    ".config/starship.toml"
    ".config/nitrogen"
    ".config/awesome"
    ".config/alacritty"
    ".config/polybar"
    ".config/picom"
)

if [ ! -d "$HOME/.config" ]
then
	echo "Creating .config directory in $HOME"
	mkdir ~/.config
fi

# Remove dotfiles in home, symlink to .dotfiles repo
echo "Symlinking dotfiles to \$HOME"
for dotfile in "${dotfiles[@]}"; do
	rm -rf ~/$dotfile
	ln -sf $dotfiles_path/$dotfile ~/$dotfile
done
